// Generated by LispyScript v1.0.0
var xl = require('xlsx');
var sheet_name = null;
var book_name = null;
var sheetsSet ;
const setBookName = function(BookName){
    book_name = BookName
}

const setSheetName = function(SheetName){
    sheet_name = SheetName
}

const getSheetNames = function(BookName){
    setBookName(BookName)
    let data = []
    let workbook = xl.readFile(BookName);
    for(let key in workbook.Sheets){
        data.push(key)
    }
    sheetsSet = data
    return data
}

const getRecord = function(rollNumber){
    var workbook = xl.readFile(book_name);
    var sheet_name_list = workbook.SheetNames;
    var response = []
    var xlData = xl.utils.sheet_to_json(workbook.Sheets[sheet_name_list[sheetsSet.indexOf(sheet_name)]]);
    for(let x in xlData){
        if(xlData[x].Rollnumber == rollNumber){
            return xlData[x]
        }
    }
    return "NA"
}

const getAttendanceFeilds = function(stuRecord){
    let data = {}
    let workingDays = {}
    for(let key in stuRecord)
        if(getMonth(key))   
            workingDays[getMonth(key)] = 0
    for(let key in stuRecord){
        if(getMonth(key)){
            if(stuRecord[key] == "P"){
                data[getMonth(key)] = (data[getMonth(key)]) ? data[getMonth(key)] + 1 : 1
            }
            else if(stuRecord[key] == "A"){
                data[getMonth(key)] = (data[getMonth(key)]) ? data[getMonth(key)] + 0 : 0
            }
            workingDays[getMonth(key)]++
        }
    }
    data.workingDays = workingDays
    return data
}

const mnthly_and_total_att = function(data){
    return {
        monthly: data, 
        total : function(){
            let total = 0
            for(let key in data){
                total += data[key]
            }
        }
    }
}

const getMonth = function(date){
    if(validateDate(date))
        return (date.split("/"))[1]
    return false
} 

const validateDate = function(testdate) {
    var date_regex = /^\d{2}\/\d{2}\/\d{4}$/ ;
    return date_regex.test(testdate);
}

const mainexe = function(rcd){
    let record = getRecord(rcd)
    if(record == "NA")
        return "NA"
    let stuRecord = getAttendanceFeilds(record)
    return {name: record.Name,roll:record.Rollnumber,Attendence: stuRecord}
}

exports.getSheetNames = getSheetNames
exports.setSheetName = setSheetName
exports.mainexe = mainexe